# Generated by Django 4.1.7 on 2023-03-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together=set(),
        ),
    ]
