# Generated by Django 4.1.7 on 2023-03-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
